# Generated by Django 3.2 on 2021-05-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
    ]
